In [1]:
import numpy as np
import pandas as pd


In [2]:
from lightautoml.reader.gpu.cudf_reader import CudfReader
from lightautoml.reader.base import PandasToPandasReader

from lightautoml.transformers.base import SequentialTransformer

from lightautoml.pipelines.utils import get_columns_by_role

from lightautoml.transformers.gpu import numeric_gpu, categorical_gpu, datetime_gpu
from lightautoml.transformers import numeric, categorical, datetime

from lightautoml.tasks import Task
from lightautoml.automl.presets.tabular_presets import TabularAutoML, TabularUtilizedAutoML

import pandas as pd
import time
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv('../../data/small_new/multioutput/ENB2012_data.csv')

tr_data, te_data = train_test_split(
    data, 
    test_size=0.2,  
    random_state=42
)

roles = {
    "target": {'Y1', 'Y2'},
}

In [4]:
adv_roles = True

In [5]:
# Imports from our package
from lightautoml.automl.base import AutoML


from lightautoml.pipelines.features.gpu.lgb_pipeline_gpu import LGBSimpleFeaturesGPU, LGBAdvancedPipelineGPU
from lightautoml.pipelines.features.gpu.linear_pipeline_gpu import LinearFeaturesGPU

from lightautoml.pipelines.features.lgb_pipeline import LGBSimpleFeatures, LGBAdvancedPipeline
from lightautoml.pipelines.features.linear_pipeline import LinearFeatures


from lightautoml.ml_algo.gpu.boost_cb_gpu import BoostCBGPU
from lightautoml.ml_algo.gpu.boost_xgb_gpu import BoostXGB
from lightautoml.ml_algo.gpu.linear_gpu import LinearLBFGSGPU

from lightautoml.ml_algo.boost_cb import BoostCB
from lightautoml.ml_algo.linear_sklearn import LinearLBFGS
from lightautoml.ml_algo.linear_sklearn import LinearL1CD


from lightautoml.pipelines.ml.base import MLPipeline
from lightautoml.pipelines.selection.importance_based import ModelBasedImportanceEstimator, ImportanceCutoffSelector

## TabularAutoML

In [6]:
task = Task('multi:reg')

multi:reg isn`t supported in lgb


In [7]:
automl = TabularAutoML(
    task = task, 
    timeout = 3600,
    cpu_limit = 4,
    reader_params = {'n_jobs': 4, 'cv': 3, 'random_state': 42},
    general_params = {'use_algos': [['linear_l2', 'cb']]}
)

In [8]:
oof_pred = automl.fit_predict(data, roles = roles, verbose = 2)

[17:19:27] Stdout logging level is INFO2.
[17:19:27] Copying TaskTimer may affect the parent PipelineTimer, so copy will create new unlimited TaskTimer
[17:19:27] Task: multi:reg

[17:19:27] Start automl preset with listed constraints:
[17:19:27] - time: 3600.00 seconds
[17:19:27] - CPU: 4 cores
[17:19:27] - memory: 16 GB

[17:19:27] Train data shape: (768, 10)

[17:19:31] Feats was rejected during automatic roles guess: []
[17:19:31] Layer 1 train process start. Time left 3596.78 secs
[17:19:31] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[17:19:31] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[17:19:31] ===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[17:19:32] ===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[17:19:32] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -2.099132272551457
[17:19:32] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[17:19:32] Time left 3595.10 secs



/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[17:19:33] Selector_CatBoost fitting and predicting completed
[17:19:33] Start fitting Lvl_0_Pipe_1_Mod_0_CatBoost ...
[17:19:33] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_0_CatBoost =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[17:19:33] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_0_CatBoost =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[17:19:33] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_0_CatBoost =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[17:19:34] Fitting Lvl_0_Pipe_1_Mod_0_CatBoost finished. score = -0.3494882974897825
[17:19:34] Lvl_0_Pipe_1_Mod_0_CatBoost fitting and predicting completed
[17:19:34] Time left 3593.81 secs

[17:19:34] Layer 1 training completed.

[17:19:34] Blending: optimization starts with equal weights and score -1.111971659796934
[17:19:34] Blending: iteration 0: score = -0.3494882974897825, weights = [0. 1.]
[17:19:34] Blending: iteration 1: score = -0.3494882974897825, weights = [0. 1.]
[17:19:34] Blending: no score update. Terminated

[17:19:34] Automl preset training completed in 6.20 seconds

[17:19:34] Model description:
Final prediction for new objects (level 0) = 
	 1.00000 * (3 averaged models Lvl_0_Pipe_1_Mod_0_CatBoost) 



In [9]:
from lightautoml.automl.presets.gpu.tabular_gpu_presets import TabularAutoMLGPU, TabularUtilizedAutoMLGPU
from lightautoml.tasks import Task

In [10]:
task = Task('multi:reg', device='gpu', metric='mse')

[17:19:39] cuml doesn't support in general case mae and will not be used.
multi:reg isn`t supported in lgb
[17:19:41] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


In [11]:
automl_gpu = TabularAutoMLGPU(
    task = task, 
    timeout = 3600,
    cpu_limit = 1,
    reader_params = {'n_jobs': 1, 'cv': 3, 'random_state': 42},
    general_params = {'use_algos': [['xgb', 'linear_l2', 'pb', 'xgb_tuned', 'pb_tuned']]}
)

In [12]:
oof_pred_gpu = automl_gpu.fit_predict(data, roles = roles, verbose = 2)

[17:19:41] Stdout logging level is INFO2.
[17:19:41] Task: multi:reg

[17:19:41] Start automl preset with listed constraints:
[17:19:41] - time: 3600.00 seconds
[17:19:41] - CPU: 1 cores
[17:19:41] - memory: 16 GB

[17:19:41] Train data shape: (768, 10)
Feats was rejected during automatic roles guess: []
[17:19:41] Layer 1 train process start. Time left 3599.57 secs
[17:19:41] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[17:19:41] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[17:19:43] Linear model: C = 1e-05 score = -85.52927641299286
[17:19:43] Linear model: C = 5e-05 score = -78.13185760345395
[17:19:43] Linear model: C = 0.0001 score = -70.28450565106685
[17:19:43] Linear model: C = 0.0005 score = -34.993639695322564
[17:19:43] Linear model: C = 0.001 score = -22.86946493781724
[17:19:44] Linear model: C = 0.005 score = -13.618768692783274
[17:19:44] Linear model: C = 0.01 score = -11.879041445478167
[17:19:44] Linear model: C = 0.05 score = -9.709

[17:22:10] Lvl_0_Pipe_1_Mod_1_Tuned_XGB fitting and predicting completed
[17:22:10] Start fitting Lvl_0_Pipe_1_Mod_1_Tuned_XGB ...
[17:22:10] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_1_Tuned_XGB (orig) =====
[17:22:16] Lvl_0_Pipe_1_Mod_1_Tuned_XGB fitting and predicting completed
[17:22:16] Start fitting Lvl_0_Pipe_1_Mod_1_Tuned_XGB ...
[17:22:16] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_1_Tuned_XGB (orig) =====
[17:22:19] Lvl_0_Pipe_1_Mod_1_Tuned_XGB fitting and predicting completed
[17:22:19] Start fitting Lvl_0_Pipe_1_Mod_1_Tuned_XGB ...
[17:22:19] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_1_Tuned_XGB (orig) =====
[17:22:31] Lvl_0_Pipe_1_Mod_1_Tuned_XGB fitting and predicting completed
[17:22:31] Start fitting Lvl_0_Pipe_1_Mod_1_Tuned_XGB ...
[17:22:31] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_1_Tuned_XGB (orig) =====
[17:22:37] Lvl_0_Pipe_1_Mod_1_Tuned_XGB fitting and predicting completed
[17:22:37] Start fitting Lvl_0_Pipe_1_Mod_1_Tun

[17:25:19] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_1_Tuned_XGB (orig) =====
[17:25:20] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_1_Tuned_XGB (orig) =====
[17:25:21] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_1_Tuned_XGB (orig) =====
[17:25:22] Lvl_0_Pipe_1_Mod_1_Tuned_XGB fitting and predicting completed
[17:25:22] Start fitting Lvl_0_Pipe_1_Mod_2_PB ...
[17:25:22] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_2_PB (orig) =====
[17:25:24] Stdout logging level is INFO.
[17:25:24] GDBT train starts. Max iter 100, early stopping rounds 100
[17:25:24] Iter 0; Sample 0, rmse = 9.214264663997513; 
[17:25:25] Iter 99; Sample 0, rmse = 2.604936765819698; 
[17:25:25] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_2_PB (orig) =====
[17:25:25] Stdout logging level is INFO.
[17:25:25] GDBT train starts. Max iter 100, early stopping rounds 100
[17:25:25] Iter 0; Sample 0, rmse = 9.95518684858441; 
[17:25:25] Iter 99; Sample 0, rmse = 2.766829980361939;

[17:25:38] Iter 0; Sample 0, rmse = 9.19244196499734; 
[17:25:39] Iter 99; Sample 0, rmse = 2.310876371118523; 
[17:25:39] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:25:39] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:25:39] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:25:39] Stdout logging level is INFO.
[17:25:39] GDBT train starts. Max iter 100, early stopping rounds 100
[17:25:39] Iter 0; Sample 0, rmse = 9.196987275294846; 
[17:25:40] Iter 99; Sample 0, rmse = 2.2558083944947374; 
[17:25:40] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:25:40] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:25:40] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:25:41] Stdout logging level is INFO.
[17:25:41] GDBT train starts. Max iter 100, early stopping rounds 100
[17:25:41] Iter 0; Sample 0, rmse = 9.197579498347197; 
[17:25:42] Iter 99; Sample 0, rmse = 2.1801801492822817; 
[17:

[17:25:56] Iter 0; Sample 0, rmse = 9.197579507331735; 
[17:25:57] Iter 99; Sample 0, rmse = 2.252408396899672; 
[17:25:57] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:25:57] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:25:57] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:25:57] Stdout logging level is INFO.
[17:25:57] GDBT train starts. Max iter 100, early stopping rounds 100
[17:25:57] Iter 0; Sample 0, rmse = 9.19928549716444; 
[17:25:58] Iter 99; Sample 0, rmse = 2.0498362502046548; 
[17:25:58] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:25:58] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:25:58] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:25:58] Stdout logging level is INFO.
[17:25:58] GDBT train starts. Max iter 100, early stopping rounds 100
[17:25:58] Iter 0; Sample 0, rmse = 9.197579607760607; 
[17:25:59] Iter 99; Sample 0, rmse = 2.062099965692955; 
[17:2

[17:26:14] Iter 0; Sample 0, rmse = 9.199425985757786; 
[17:26:15] Iter 99; Sample 0, rmse = 2.171119048131002; 
[17:26:15] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:26:15] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:26:15] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:26:15] Stdout logging level is INFO.
[17:26:15] GDBT train starts. Max iter 100, early stopping rounds 100
[17:26:15] Iter 0; Sample 0, rmse = 9.198713826391403; 
[17:26:16] Iter 99; Sample 0, rmse = 2.0875836905040073; 
[17:26:16] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:26:16] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:26:16] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:26:16] Stdout logging level is INFO.
[17:26:16] GDBT train starts. Max iter 100, early stopping rounds 100
[17:26:16] Iter 0; Sample 0, rmse = 9.192708883429459; 
[17:26:17] Iter 99; Sample 0, rmse = 2.422494632877488; 
[17:

[17:26:30] Iter 0; Sample 0, rmse = 9.198713774685501; 
[17:26:31] Iter 99; Sample 0, rmse = 2.193990533504077; 
[17:26:31] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:26:31] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:26:31] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:26:31] Stdout logging level is INFO.
[17:26:31] GDBT train starts. Max iter 100, early stopping rounds 100
[17:26:31] Iter 0; Sample 0, rmse = 9.199426023299132; 
[17:26:32] Iter 99; Sample 0, rmse = 2.2094427796641387; 
[17:26:32] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:26:32] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:26:32] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:26:32] Stdout logging level is INFO.
[17:26:32] GDBT train starts. Max iter 100, early stopping rounds 100
[17:26:32] Iter 0; Sample 0, rmse = 9.192442411282505; 
[17:26:33] Iter 99; Sample 0, rmse = 2.047057749186565; 
[17:

[17:26:49] Iter 0; Sample 0, rmse = 9.192442585035451; 
[17:26:50] Iter 99; Sample 0, rmse = 2.1040932978206937; 
[17:26:50] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:26:50] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:26:50] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:26:50] Stdout logging level is INFO.
[17:26:50] GDBT train starts. Max iter 100, early stopping rounds 100
[17:26:50] Iter 0; Sample 0, rmse = 9.198348566613225; 
[17:26:51] Iter 99; Sample 0, rmse = 2.045013554212721; 
[17:26:51] Lvl_0_Pipe_1_Mod_3_Tuned_PB fitting and predicting completed
[17:26:51] Start fitting Lvl_0_Pipe_1_Mod_3_Tuned_PB ...
[17:26:51] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_3_Tuned_PB (orig) =====
[17:26:51] Stdout logging level is INFO.
[17:26:51] GDBT train starts. Max iter 100, early stopping rounds 100
[17:26:51] Iter 0; Sample 0, rmse = 9.192582559516108; 
[17:26:52] Iter 99; Sample 0, rmse = 2.1758478847222316; 
[17

[17:27:09] Blending, iter 1: score = -1.7791436220933878, weights = [0.08088205 0.         0.55374014 0.         0.36537784]
[17:27:09] Blending, iter 2: score = -1.7791436690870726, weights = [0.0808629  0.         0.55384576 0.         0.36529136]
[17:27:09] Blending, iter 3: score = -1.7791436690870726, weights = [0.0808629  0.         0.55384576 0.         0.36529136]
[17:27:09] No score update. Terminated
[17:27:09] Automl preset training completed in 448.50 seconds

[17:27:09] Model description:
Final prediction for new objects (level 0) = 
	 0.08086 * (3 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.55385 * (3 averaged models Lvl_0_Pipe_1_Mod_1_Tuned_XGB) +
	 0.36529 * (3 averaged models Lvl_0_Pipe_1_Mod_3_Tuned_PB) 



In [13]:
gpu_inf = automl_gpu.predict(data)

In [14]:
automl_gpu.to_cpu()

TabularAutoMLGPU
{'data_size': 28, 'categorical_idx': {'int': [26, 27], 'str': ['le__X7', 'le__X4']}, 'embed_sizes': array([5, 5], dtype=int32), 'output_size': 2, 'cs': [1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000, 5000, 10000, 50000, 100000], 'max_iter': 100, 'tol': 1e-06, 'early_stopping': 2, 'loss': TorchLossWrapper(
  (base_loss): L1Loss()
), 'metric': <lightautoml.tasks.losses.base.MetricFunc object at 0x7f047844f7c0>, 'model': CatRegression(
  (linear): Linear(in_features=26, out_features=2, bias=False)
)}
TorchBasedLinearRegression
{'_name': 'multi:reg', 'device': 'gpu', 'losses': {'lgb': <lightautoml.tasks.losses.lgb.LGBLoss object at 0x7f047df5e430>, 'sklearn': <lightautoml.tasks.losses.sklearn.SKLoss object at 0x7f047df5e790>, 'torch': <lightautoml.tasks.losses.torch.TORCHLoss object at 0x7f047df5e9d0>, 'cb': <lightautoml.tasks.losses.cb.CBLoss object at 0x7f047844f310>, 'torch_gpu': <lightautoml.tasks.losses.gpu.torch_gpu.TO

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/98 [00:00<?, ?it/s]

[17:27:10] cuml doesn't support in general case mae and will not be used.
multi:reg isn`t supported in lgb
[17:27:10] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


In [15]:
cpu_inf = automl_gpu.predict(data)

In [16]:
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
import cudf

cluster = LocalCUDACluster(rmm_managed_memory=True, CUDA_VISIBLE_DEVICES="0",
                               protocol="ucx", enable_nvlink=True,
                               memory_limit="8GB")
print("dashboard:", cluster.dashboard_link)
client = Client(cluster)
client.run(cudf.set_allocator, "managed")

/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/comm/ucx.py:61: UserWarning: A CUDA context for device 0 already exists on process ID 26134. This is often the result of a CUDA-enabled library calling a CUDA runtime function before Dask-CUDA can spawn worker processes. Please make sure any such function calls don't happen at import time or in the global scope of a program.
  warnings.warn(
2022-11-30 17:27:13,070 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-11-30 17:27:13,070 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize


dashboard: http://127.0.0.1:8787/status


{'ucx://127.0.0.1:45417': None}

In [17]:
task = Task('multi:reg', device='mgpu')

automl_mgpu = TabularAutoMLGPU(
    task = task, 
    timeout = 3600,
    cpu_limit = 1,
    reader_params = {'n_jobs': 1, 'cv': 3, 'random_state': 42, 'npartitions': 2},
    general_params = {'use_algos': [['xgb', 'linear_l2']]},
    client = client
)

[17:27:13] cuml doesn't support in general case mae and will not be used.
multi:reg isn`t supported in lgb
[17:27:13] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


In [18]:
oof_pred_mgpu = automl_mgpu.fit_predict(data, roles = roles, verbose = 2)

[17:27:13] Stdout logging level is INFO2.
[17:27:13] Task: multi:reg

[17:27:13] Start automl preset with listed constraints:
[17:27:13] - time: 3600.00 seconds
[17:27:13] - CPU: 1 cores
[17:27:13] - memory: 16 GB

[17:27:13] Train data shape: (768, 10)
Feats was rejected during automatic roles guess: []
[17:27:14] Layer 1 train process start. Time left 3599.63 secs
[17:27:14] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[17:27:14] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
Score: -8.36949348449707
Score: -7.84108829498291
Score: -7.28300666809082
Score: -4.609966278076172
Score: -3.6016383171081543
Score: -2.433990001678467
Score: -2.266366958618164
Score: -2.0033316612243652
Score: -1.9246456623077393
Score: -1.8615055084228516
Score: -1.8663086891174316
Score: -1.8519073724746704
Score: -1.8572559356689453
Score: -1.8469343185424805
Score: -1.8473196029663086
Score: -1.8474206924438477
[17:27:18] ===== Start working with fold 1 for Lvl_0_Pipe_0_Mod

/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[17:27:31] task [xgboost.dask-0]:ucx://127.0.0.1:45417 got new rank 0


[17:27:37] Selector_XGB fitting and predicting completed
[17:27:37] Start fitting Lvl_0_Pipe_1_Mod_0_XGB ...
[17:27:37] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_0_XGB (orig) =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[17:27:37] task [xgboost.dask-0]:ucx://127.0.0.1:45417 got new rank 0


[17:27:46] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_0_XGB (orig) =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[17:27:46] task [xgboost.dask-0]:ucx://127.0.0.1:45417 got new rank 0


[17:27:54] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_0_XGB (orig) =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[17:27:54] task [xgboost.dask-0]:ucx://127.0.0.1:45417 got new rank 0


[17:27:57] Lvl_0_Pipe_1_Mod_0_XGB fitting and predicting completed
[17:27:57] Time left 3555.85 secs

[17:27:57] Layer 1 training completed.

[17:27:57] Blending: Optimization starts with equal weights and score -1.2585754712174335
[17:27:58] Blending, iter 0: score = -0.9896841814989845, weights = [0.07295163 0.9270484 ]
[17:27:58] Blending, iter 1: score = -0.9896841814989845, weights = [0.07295163 0.9270484 ]
[17:27:58] No score update. Terminated
[17:27:58] Automl preset training completed in 44.27 seconds

[17:27:58] Model description:
Final prediction for new objects (level 0) = 
	 0.07295 * (3 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.92705 * (3 averaged models Lvl_0_Pipe_1_Mod_0_XGB) 



In [19]:
print(cpu_inf.data.T)
print()
print(gpu_inf.data.T)
print()
print(oof_pred_gpu.data.T)
print()
print(oof_pred.data.T)
print()
print(oof_pred_mgpu.data.T)

[[17.991678 17.991678 17.991678 ... 16.450613 16.450613 16.450613]
 [23.666157 23.666157 23.666157 ... 17.486124 17.486124 17.486124]]

[[16.845493 16.957912 16.75364  ... 16.930658 16.82767  16.705229]
 [22.603188 22.45641  22.628407 ... 17.412346 17.0728   16.980103]]

[[18.379612 18.519882 16.599361 ... 17.033802 16.711424 16.081863]
 [25.225676 24.961517 21.570883 ... 17.465443 17.112862 16.446402]]

[[15.770237 15.915673 15.78574  ... 16.53469  16.339546 16.176693]
 [22.325417 21.209105 21.430384 ... 16.482996 15.88877  16.432215]]

[[16.073336 16.523046 15.753998 ... 17.105915 17.053154 14.807506]
 [24.212898 23.914293 21.375853 ... 17.591034 17.280005 16.680828]]
