In [1]:
import os


a = os.environ['OMP_NUM_THREADS'] = "8"

import numpy as np
import pandas as pd

In [2]:
from lightautoml_gpu.reader.gpu.cudf_reader import CudfReader
from lightautoml_gpu.reader.base import PandasToPandasReader

from lightautoml_gpu.transformers.base import SequentialTransformer

from lightautoml_gpu.pipelines.utils import get_columns_by_role

from lightautoml_gpu.transformers.gpu import numeric_gpu, categorical_gpu, datetime_gpu
from lightautoml_gpu.transformers import numeric, categorical, datetime

from lightautoml_gpu.tasks import Task
from lightautoml_gpu.automl.presets.tabular_presets import TabularAutoML, TabularUtilizedAutoML

import pandas as pd
import time
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv('../../data/small_new/multioutput/ENB2012_data.csv')

tr_data, te_data = train_test_split(
    data, 
    test_size=0.2,  
    random_state=42
)

roles = {
    "target": {'Y1', 'Y2'},
}

In [4]:
adv_roles = True

In [5]:
# Imports from our package
from lightautoml_gpu.automl.base import AutoML


from lightautoml_gpu.pipelines.features.gpu.lgb_pipeline_gpu import LGBSimpleFeaturesGPU, LGBAdvancedPipelineGPU
from lightautoml_gpu.pipelines.features.gpu.linear_pipeline_gpu import LinearFeaturesGPU

from lightautoml_gpu.pipelines.features.lgb_pipeline import LGBSimpleFeatures, LGBAdvancedPipeline
from lightautoml_gpu.pipelines.features.linear_pipeline import LinearFeatures


from lightautoml_gpu.ml_algo.gpu.boost_cb_gpu import BoostCBGPU
from lightautoml_gpu.ml_algo.gpu.boost_xgb_gpu import BoostXGB
from lightautoml_gpu.ml_algo.gpu.linear_gpu import LinearLBFGSGPU

from lightautoml_gpu.ml_algo.boost_cb import BoostCB
from lightautoml_gpu.ml_algo.linear_sklearn import LinearLBFGS
from lightautoml_gpu.ml_algo.linear_sklearn import LinearL1CD


from lightautoml_gpu.pipelines.ml.base import MLPipeline
from lightautoml_gpu.pipelines.selection.importance_based import ModelBasedImportanceEstimator, ImportanceCutoffSelector

## TabularAutoML

In [6]:
task = Task('multi:reg', loss = 'mse')

multi:reg isn`t supported in lgb


In [7]:
automl = TabularAutoML(
    task = task, 
    timeout = 3600,
    cpu_limit = 4,
    reader_params = {'n_jobs': 4, 'cv': 3, 'random_state': 42},
    general_params = {'use_algos': [['linear_l2', 'cb']]}
)

In [8]:
oof_pred = automl.fit_predict(data, roles = roles, verbose = 2)

[13:47:33] Stdout logging level is INFO2.
[13:47:33] Copying TaskTimer may affect the parent PipelineTimer, so copy will create new unlimited TaskTimer
[13:47:33] Task: multi:reg

[13:47:33] Start automl preset with listed constraints:
[13:47:33] - time: 3600.00 seconds
[13:47:33] - CPU: 4 cores
[13:47:33] - memory: 16 GB

[13:47:33] Train data shape: (768, 10)

[13:47:36] Feats was rejected during automatic roles guess: []
[13:47:36] Layer 1 train process start. Time left 3596.73 secs
[13:47:36] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[13:47:36] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[13:47:36] ===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[13:47:37] ===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[13:47:37] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -2.1695059866706523
[13:47:37] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[13:47:37] Time left 3595.84 secs



/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[13:47:37] Selector_CatBoost fitting and predicting completed
[13:47:37] Start fitting Lvl_0_Pipe_1_Mod_0_CatBoost ...
[13:47:37] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_0_CatBoost =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[13:47:38] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_0_CatBoost =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[13:47:38] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_0_CatBoost =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[13:47:38] Fitting Lvl_0_Pipe_1_Mod_0_CatBoost finished. score = -0.3494882974897825
[13:47:38] Lvl_0_Pipe_1_Mod_0_CatBoost fitting and predicting completed
[13:47:38] Time left 3594.39 secs

[13:47:38] Layer 1 training completed.

[13:47:38] Blending: optimization starts with equal weights and score -1.1413262737418224
[13:47:38] Blending: iteration 0: score = -0.3494882974897825, weights = [0. 1.]
[13:47:39] Blending: iteration 1: score = -0.3494882974897825, weights = [0. 1.]
[13:47:39] Blending: no score update. Terminated

[13:47:39] Automl preset training completed in 5.63 seconds

[13:47:39] Model description:
Final prediction for new objects (level 0) = 
	 1.00000 * (3 averaged models Lvl_0_Pipe_1_Mod_0_CatBoost) 



In [9]:
from lightautoml_gpu.automl.presets.gpu.tabular_gpu_presets import TabularAutoMLGPU, TabularUtilizedAutoMLGPU
from lightautoml_gpu.tasks import Task

In [10]:
task = Task('multi:reg', loss = 'mse', device='gpu')

multi:reg isn`t supported in lgb
[13:47:46] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


In [11]:
automl_gpu = TabularAutoMLGPU(
    task = task, 
    timeout = 3600,
    cpu_limit = 1,
    reader_params = {'n_jobs': 1, 'cv': 3, 'random_state': 42},
    general_params = {'use_algos': [['xgb', 'linear_l2', 'pb']]}
)

In [12]:
oof_pred_gpu = automl_gpu.fit_predict(data, roles = roles, verbose = 2)

[13:47:46] Stdout logging level is INFO2.
[13:47:46] Task: multi:reg

[13:47:46] Start automl preset with listed constraints:
[13:47:46] - time: 3600.00 seconds
[13:47:46] - CPU: 1 cores
[13:47:46] - memory: 16 GB

[13:47:46] Train data shape: (768, 10)
[13:47:46] Feats was rejected during automatic roles guess: []
[13:47:46] Layer 1 train process start. Time left 3599.56 secs
[13:47:47] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[13:47:47] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[13:47:49] ===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[13:47:51] ===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[13:47:52] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -1.9745038881401222
[13:47:52] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[13:47:52] Time left 3593.69 secs

[13:47:54] Stdout logging level is INFO.
[13:47:54] GDBT train starts. Max iter 3000, early stopping rounds

[13:48:58] Blending, iter 2: score = -0.9537503526235621, weights = [0.06871326 0.7206321  0.21065466]
[13:48:58] Blending, iter 3: score = -0.9537503526235621, weights = [0.06871326 0.7206321  0.21065466]
[13:48:58] No score update. Terminated
[13:48:58] Automl preset training completed in 71.86 seconds

[13:48:58] Model description:
Final prediction for new objects (level 0) = 
	 0.06871 * (3 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.72063 * (3 averaged models Lvl_0_Pipe_1_Mod_0_XGB) +
	 0.21065 * (3 averaged models Lvl_0_Pipe_1_Mod_1_PB) 



In [13]:
gpu_inf = automl_gpu.predict(data)

In [14]:
automl_gpu.to_cpu()

multi:reg isn`t supported in lgb
[13:40:18] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


  0%|          | 0/2997 [00:00<?, ?it/s]

  0%|          | 0/2742 [00:00<?, ?it/s]

  0%|          | 0/2112 [00:00<?, ?it/s]

multi:reg isn`t supported in lgb
[13:40:22] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


In [15]:
cpu_inf = automl_gpu.predict(data)

In [16]:
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
import cudf

cluster = LocalCUDACluster(rmm_managed_memory=True, CUDA_VISIBLE_DEVICES="0",
                               protocol="ucx", enable_nvlink=True,
                               memory_limit="8GB")
print("dashboard:", cluster.dashboard_link)
client = Client(cluster)
client.run(cudf.set_allocator, "managed")

/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/comm/ucx.py:61: UserWarning: A CUDA context for device 0 already exists on process ID 13097. This is often the result of a CUDA-enabled library calling a CUDA runtime function before Dask-CUDA can spawn worker processes. Please make sure any such function calls don't happen at import time or in the global scope of a program.
  warnings.warn(
2022-12-10 13:40:24,902 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-kgdbqb4r', purging
2022-12-10 13:40:24,902 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-12-10 13:40:24,902 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize


dashboard: http://127.0.0.1:8787/status


{'ucx://127.0.0.1:51957': None}

In [17]:
task = Task('multi:reg', loss = 'mse', device='mgpu')

automl_mgpu = TabularAutoMLGPU(
    task = task, 
    timeout = 3600,
    cpu_limit = 1,
    reader_params = {'n_jobs': 1, 'cv': 3, 'random_state': 42, 'npartitions': 2},
    general_params = {'use_algos': [['xgb', 'linear_l2']]},
    client = client
)

multi:reg isn`t supported in lgb
[13:40:25] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


In [18]:
oof_pred_mgpu = automl_mgpu.fit_predict(data, roles = roles, verbose = 2)

[13:40:25] Stdout logging level is INFO2.
[13:40:25] Task: multi:reg

[13:40:25] Start automl preset with listed constraints:
[13:40:25] - time: 3600.00 seconds
[13:40:25] - CPU: 1 cores
[13:40:25] - memory: 16 GB

[13:40:25] Train data shape: (768, 10)
[13:40:25] Feats was rejected during automatic roles guess: []
[13:40:25] Layer 1 train process start. Time left 3599.63 secs
[13:40:26] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[13:40:26] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[13:40:27] ===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[13:40:29] ===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[13:40:30] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -1.987997462488711
[13:40:30] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[13:40:30] Time left 3594.93 secs

[13:40:30] Stdout logging level is INFO.
[13:40:30] GDBT train starts. Max iter 3000, early stopping rounds 

/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[13:40:48] task [xgboost.dask-0]:ucx://127.0.0.1:51957 got new rank 0


[13:40:56] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_0_XGB (orig) =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[13:40:56] task [xgboost.dask-0]:ucx://127.0.0.1:51957 got new rank 0


[13:41:04] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_0_XGB (orig) =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[13:41:05] task [xgboost.dask-0]:ucx://127.0.0.1:51957 got new rank 0


[13:41:07] Fitting Lvl_0_Pipe_1_Mod_0_XGB finished. score = -1.4210363074888785
[13:41:07] Lvl_0_Pipe_1_Mod_0_XGB fitting and predicting completed
[13:41:07] Time left 3558.30 secs

[13:41:07] Layer 1 training completed.

[13:41:07] Blending: Optimization starts with equal weights and score -1.5198859591657916
[13:41:07] Blending, iter 0: score = -1.3705565962319572, weights = [0.14589803 0.85410196]
[13:41:07] Blending, iter 1: score = -1.3705565962319572, weights = [0.14589803 0.85410196]
[13:41:07] No score update. Terminated
[13:41:07] Automl preset training completed in 41.85 seconds

[13:41:07] Model description:
Final prediction for new objects (level 0) = 
	 0.14590 * (3 averaged models Lvl_0_Pipe_0_Mod_0_LinearL2) +
	 0.85410 * (3 averaged models Lvl_0_Pipe_1_Mod_0_XGB) 



In [19]:
print(cpu_inf.data.T)
print()
print(gpu_inf.data.T)
print()
print(oof_pred_gpu.data.T)
print()
print(oof_pred.data.T)
print()
print(oof_pred_mgpu.data.T)

[[21.592127 20.911577 21.538649 ... 17.80141  16.999327 16.89115 ]
 [16.273535 16.558796 15.514778 ... 17.351414 17.059956 16.524736]]

[[21.592134 20.911587 21.538649 ... 17.801424 16.999352 16.891197]
 [16.27357  16.558823 15.514776 ... 17.351433 17.05996  16.52476 ]]

[[22.084217 23.090494 20.3359   ... 17.556313 16.952316 16.56749 ]
 [17.585676 16.95052  15.522291 ... 17.295746 16.689827 16.334679]]

[[22.325417 21.209105 21.430384 ... 16.482996 15.88877  16.432215]
 [15.770237 15.915673 15.78574  ... 16.53469  16.339546 16.176693]]

[[23.569838 23.603844 21.206917 ... 17.79602  17.50906  17.473864]
 [16.294819 16.225418 15.455781 ... 17.205748 16.966179 17.177782]]


In [20]:
cluster.close()

In [22]:
client.close()