In [1]:
import os


a = os.environ['OMP_NUM_THREADS'] = "8"

import numpy as np
import pandas as pd

In [2]:
from lightautoml_gpu.reader.gpu.cudf_reader import CudfReader
from lightautoml_gpu.reader.base import PandasToPandasReader

from lightautoml_gpu.transformers.base import SequentialTransformer

from lightautoml_gpu.pipelines.utils import get_columns_by_role

from lightautoml_gpu.transformers.gpu import numeric_gpu, categorical_gpu, datetime_gpu
from lightautoml_gpu.transformers import numeric, categorical, datetime

from lightautoml_gpu.tasks import Task
from lightautoml_gpu.automl.presets.tabular_presets import TabularAutoML, TabularUtilizedAutoML

import pandas as pd
import time
from sklearn.model_selection import train_test_split

Level "INFO2: 17" already defined, skipping...
Level "INFO3: 13" already defined, skipping...


In [3]:
data = pd.read_csv('../../data/small_new/multioutput/ENB2012_data.csv')

tr_data, te_data = train_test_split(
    data, 
    test_size=0.2,  
    random_state=42
)

roles = {
    "target": {'Y1', 'Y2'},
}

In [4]:
adv_roles = True

In [5]:
# Imports from our package
from lightautoml_gpu.automl.base import AutoML


from lightautoml_gpu.pipelines.features.gpu.lgb_pipeline_gpu import LGBSimpleFeaturesGPU, LGBAdvancedPipelineGPU
from lightautoml_gpu.pipelines.features.gpu.linear_pipeline_gpu import LinearFeaturesGPU

from lightautoml_gpu.pipelines.features.lgb_pipeline import LGBSimpleFeatures, LGBAdvancedPipeline
from lightautoml_gpu.pipelines.features.linear_pipeline import LinearFeatures


from lightautoml_gpu.ml_algo.gpu.boost_cb_gpu import BoostCBGPU
from lightautoml_gpu.ml_algo.gpu.boost_xgb_gpu import BoostXGB
from lightautoml_gpu.ml_algo.gpu.linear_gpu import LinearLBFGSGPU

from lightautoml_gpu.ml_algo.boost_cb import BoostCB
from lightautoml_gpu.ml_algo.linear_sklearn import LinearLBFGS
from lightautoml_gpu.ml_algo.linear_sklearn import LinearL1CD


from lightautoml_gpu.pipelines.ml.base import MLPipeline
from lightautoml_gpu.pipelines.selection.importance_based import ModelBasedImportanceEstimator, ImportanceCutoffSelector

## TabularAutoML

In [10]:
task = Task('multi:reg', loss = 'mse')

multi:reg isn`t supported in lgb
[12:23:44] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


In [11]:
automl = TabularAutoML(
    task = task, 
    timeout = 3600,
    cpu_limit = 4,
    reader_params = {'n_jobs': 4, 'cv': 3, 'random_state': 42},
    general_params = {'use_algos': [['linear_l2', 'cb']]}
)

In [12]:
oof_pred = automl.fit_predict(data, roles = roles, verbose = 2)

[12:23:44] Stdout logging level is INFO2.
[12:23:44] Task: multi:reg

[12:23:44] Start automl preset with listed constraints:
[12:23:44] - time: 3600.00 seconds
[12:23:44] - CPU: 4 cores
[12:23:44] - memory: 16 GB

[12:23:44] Train data shape: (768, 10)

[12:23:54] Feats was rejected during automatic roles guess: []
[12:23:54] Layer 1 train process start. Time left 3589.25 secs
[12:23:54] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[12:23:54] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[12:23:55] ===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[12:23:55] ===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_0_LinearL2 =====
[12:23:55] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -2.1695349167287348
[12:23:55] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[12:23:55] Time left 3588.39 secs



/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[12:23:56] Selector_CatBoost fitting and predicting completed
[12:23:56] Start fitting Lvl_0_Pipe_1_Mod_0_CatBoost ...
[12:23:56] ===== Start working with fold 0 for Lvl_0_Pipe_1_Mod_0_CatBoost =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[12:23:56] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_0_CatBoost =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[12:23:56] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_0_CatBoost =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/catboost/core.py:1419: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,


[12:23:57] Fitting Lvl_0_Pipe_1_Mod_0_CatBoost finished. score = -0.3494882974897825
[12:23:57] Lvl_0_Pipe_1_Mod_0_CatBoost fitting and predicting completed
[12:23:57] Time left 3586.97 secs

[12:23:57] Layer 1 training completed.

[12:23:57] Blending: optimization starts with equal weights and score -1.1414352590714898
[12:23:57] Blending: iteration 0: score = -0.3494882974897825, weights = [0. 1.]
[12:23:57] Blending: iteration 1: score = -0.3494882974897825, weights = [0. 1.]
[12:23:57] Blending: no score update. Terminated

[12:23:57] Automl preset training completed in 13.04 seconds

[12:23:57] Model description:
Final prediction for new objects (level 0) = 
	 1.00000 * (3 averaged models Lvl_0_Pipe_1_Mod_0_CatBoost) 



In [6]:
from lightautoml_gpu.automl.presets.gpu.tabular_gpu_presets import TabularAutoMLGPU, TabularUtilizedAutoMLGPU
from lightautoml_gpu.tasks import Task

In [7]:
task = Task('multi:reg', loss = 'mse', device='gpu')

multi:reg isn`t supported in lgb


In [8]:
automl_gpu = TabularAutoMLGPU(
    task = task, 
    timeout = 3600,
    cpu_limit = 1,
    reader_params = {'n_jobs': 1, 'cv': 3, 'random_state': 42},
    general_params = {'use_algos': [['xgb', 'linear_l2', 'pb']]}
)

In [9]:
oof_pred_gpu = automl_gpu.fit_predict(data, roles = roles, verbose = 2)

[12:22:21] Stdout logging level is INFO2.
[12:22:21] Copying TaskTimer may affect the parent PipelineTimer, so copy will create new unlimited TaskTimer
[12:22:21] Task: multi:reg

[12:22:21] Start automl preset with listed constraints:
[12:22:21] - time: 3600.00 seconds
[12:22:21] - CPU: 1 cores
[12:22:21] - memory: 16 GB

[12:22:21] Train data shape: (768, 10)
[12:22:21] Feats was rejected during automatic roles guess: []
[12:22:21] Layer 1 train process start. Time left 3599.54 secs
[12:22:21] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[12:22:21] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[12:22:24] ===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[12:22:25] ===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[12:22:26] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -2.178004495278001
[12:22:26] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[12:22:26] Time left 3595.18 secs

[12:23:31] Iter 400; Sample 0, rmse = 1.0101994878343423; 
[12:23:31] Iter 500; Sample 0, rmse = 0.9501870156896989; 
[12:23:32] Iter 600; Sample 0, rmse = 0.92272069862858; 
[12:23:32] Iter 700; Sample 0, rmse = 0.9039473099923753; 
[12:23:32] Iter 800; Sample 0, rmse = 0.8730175083004397; 
[12:23:33] Iter 900; Sample 0, rmse = 0.8635463115830538; 
[12:23:33] Iter 1000; Sample 0, rmse = 0.8570847882229982; 
[12:23:34] Iter 1100; Sample 0, rmse = 0.848652953962316; 
[12:23:34] Iter 1200; Sample 0, rmse = 0.8404001449096732; 
[12:23:35] Iter 1300; Sample 0, rmse = 0.8311950957602734; 
[12:23:35] Iter 1400; Sample 0, rmse = 0.8283914248230217; 
[12:23:35] Iter 1500; Sample 0, rmse = 0.8257151487212716; 
[12:23:36] Iter 1600; Sample 0, rmse = 0.8239826721338911; 
[12:23:36] Iter 1700; Sample 0, rmse = 0.818299408314596; 
[12:23:37] Iter 1800; Sample 0, rmse = 0.8134062752966031; 
[12:23:37] Iter 1900; Sample 0, rmse = 0.8097145850032977; 
[12:23:37] Iter 2000; Sample 0, rmse = 0.806597995

In [13]:
gpu_inf = automl_gpu.predict(data)

In [14]:
automl_gpu.to_cpu()

multi:reg isn`t supported in lgb
[12:23:59] CatBoost supports only MultiRMSE metric and loss for multi:reg task.
multi:reg isn`t supported in lgb
[12:23:59] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


  0%|          | 0/3000 [00:00<?, ?it/s]

multi:reg isn`t supported in lgb
[12:24:00] CatBoost supports only MultiRMSE metric and loss for multi:reg task.
multi:reg isn`t supported in lgb
[12:24:01] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


  0%|          | 0/2979 [00:00<?, ?it/s]

  0%|          | 0/2996 [00:00<?, ?it/s]

  0%|          | 0/2996 [00:00<?, ?it/s]

multi:reg isn`t supported in lgb
[12:24:05] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


In [16]:
cpu_inf = automl_gpu.predict(data)

In [17]:
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
import cudf

cluster = LocalCUDACluster(rmm_managed_memory=True, CUDA_VISIBLE_DEVICES="0",
                               protocol="ucx", enable_nvlink=True,
                               memory_limit="8GB")
print("dashboard:", cluster.dashboard_link)
client = Client(cluster)
client.run(cudf.set_allocator, "managed")

/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/comm/ucx.py:61: UserWarning: A CUDA context for device 0 already exists on process ID 9363. This is often the result of a CUDA-enabled library calling a CUDA runtime function before Dask-CUDA can spawn worker processes. Please make sure any such function calls don't happen at import time or in the global scope of a program.
  warnings.warn(
2023-01-14 12:25:52,177 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-01-14 12:25:52,178 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize


dashboard: http://127.0.0.1:8787/status


{'ucx://127.0.0.1:52305': None}

In [18]:
task = Task('multi:reg', loss = 'mse', device='mgpu')

automl_mgpu = TabularAutoMLGPU(
    task = task, 
    timeout = 3600,
    cpu_limit = 1,
    reader_params = {'n_jobs': 1, 'cv': 3, 'random_state': 42, 'npartitions': 2},
    general_params = {'use_algos': [['xgb', 'linear_l2']]},
    client = client
)

multi:reg isn`t supported in lgb
[12:25:54] CatBoost supports only MultiRMSE metric and loss for multi:reg task.


In [19]:
oof_pred_mgpu = automl_mgpu.fit_predict(data, roles = roles, verbose = 2)

[12:25:56] Stdout logging level is INFO2.
[12:25:56] Task: multi:reg

[12:25:56] Start automl preset with listed constraints:
[12:25:56] - time: 3600.00 seconds
[12:25:56] - CPU: 1 cores
[12:25:56] - memory: 16 GB

[12:25:56] Train data shape: (768, 10)
[12:25:56] Feats was rejected during automatic roles guess: []
[12:25:56] Layer 1 train process start. Time left 3599.71 secs
[12:25:56] Start fitting Lvl_0_Pipe_0_Mod_0_LinearL2 ...
[12:25:56] ===== Start working with fold 0 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[12:25:57] ===== Start working with fold 1 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[12:25:58] ===== Start working with fold 2 for Lvl_0_Pipe_0_Mod_0_LinearL2 (orig) =====
[12:25:58] Fitting Lvl_0_Pipe_0_Mod_0_LinearL2 finished. score = -2.1765454036990803
[12:25:58] Lvl_0_Pipe_0_Mod_0_LinearL2 fitting and predicting completed
[12:25:58] Time left 3597.69 secs

[12:25:58] Stdout logging level is INFO.
[12:25:58] GDBT train starts. Max iter 3000, early stopping rounds

/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[12:26:21] task [xgboost.dask-0]:ucx://127.0.0.1:52305 got new rank 0


[12:26:26] ===== Start working with fold 1 for Lvl_0_Pipe_1_Mod_0_XGB (orig) =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[12:26:26] task [xgboost.dask-0]:ucx://127.0.0.1:52305 got new rank 0


[12:26:31] ===== Start working with fold 2 for Lvl_0_Pipe_1_Mod_0_XGB (orig) =====


/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/xgboost/dask.py:884: RuntimeWarning: coroutine 'Client._wait_for_workers' was never awaited
  client.wait_for_workers(n_workers)
/home/rishat/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/distributed/worker_state_machine.py:3649: FutureWarning: The `Worker.nthreads` attribute has been moved to `Worker.state.nthreads`
  warnings.warn(
[12:26:32] task [xgboost.dask-0]:ucx://127.0.0.1:52305 got new rank 0


[12:26:36] Fitting Lvl_0_Pipe_1_Mod_0_XGB finished. score = -0.5334486607213815
[12:26:36] Lvl_0_Pipe_1_Mod_0_XGB fitting and predicting completed
[12:26:36] Time left 3559.81 secs

[12:26:36] Layer 1 training completed.

[12:26:36] Blending: Optimization starts with equal weights and score -1.204309390621881
[12:26:36] Blending, iter 0: score = -0.5334486607213815, weights = [0. 1.]
[12:26:36] Blending, iter 1: score = -0.5334486607213815, weights = [0. 1.]
[12:26:36] No score update. Terminated
[12:26:36] Automl preset training completed in 40.28 seconds

[12:26:36] Model description:
Final prediction for new objects (level 0) = 
	 1.00000 * (3 averaged models Lvl_0_Pipe_1_Mod_0_XGB) 



In [20]:
print(cpu_inf.data.T)
print()
print(gpu_inf.data.T)
print()
print(oof_pred_gpu.data.T)
print()
print(oof_pred.data.T)
print()
print(oof_pred_mgpu.data.T)

[[22.523565 21.312319 21.028816 ... 16.399435 16.244144 16.245834]
 [16.196108 16.262726 15.902071 ... 16.34151  16.377163 16.371582]]

[[22.523571 21.312319 21.028824 ... 16.399435 16.244144 16.245857]
 [16.196121 16.262749 15.902094 ... 16.341505 16.377167 16.371584]]

[[23.492664 22.157509 20.964127 ... 16.419237 16.120636 16.357498]
 [17.01507  16.901182 15.929466 ... 16.257198 16.373657 16.361753]]

[[22.325417 21.209105 21.430384 ... 16.482996 15.88877  16.432215]
 [15.770237 15.915673 15.78574  ... 16.53469  16.339546 16.176693]]

[[22.363066 21.329357 20.67113  ... 16.549248 16.567663 16.55196 ]
 [15.921541 16.009209 15.802179 ... 16.367476 16.34037  16.462301]]


In [20]:
cluster.close()

In [22]:
client.close()